# Generated by Django 4.2.1 on 2023-08-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('description', models.TextField()),
            ],
        ),
    ]
