# Generated by Django 4.2.1 on 2023-08-27 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evs', '0003_candidate_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_code', models.CharField(max_length=64)),
                ('data', models.TextField()),
                ('previous_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evs.block')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evs.block')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evs.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evs.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
