# Generated by Django 4.2.1 on 2023-08-27 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0004_block_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='block',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='evs.block'),
            preserve_default=False,
        ),
    ]
