# Generated by Django 4.2.1 on 2023-08-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0005_alter_vote_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evs.block'),
        ),
    ]
