# Generated by Django 4.2.1 on 2023-08-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0008_remove_vote_block_vote_block_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='block_id',
        ),
        migrations.AddField(
            model_name='vote',
            name='block_hash_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
