# Generated by Django 4.2.1 on 2023-08-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0010_remove_vote_block_hash_code_vote_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='block',
        ),
        migrations.AddField(
            model_name='vote',
            name='block_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
