# Generated by Django 4.2.1 on 2023-08-28 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0011_remove_vote_block_vote_block_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='block_id',
        ),
        migrations.AddField(
            model_name='vote',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evs.block'),
        ),
    ]
