# Generated by Django 4.2.1 on 2023-08-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0012_remove_vote_block_id_vote_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='nonce',
            field=models.CharField(default='', max_length=64),
        ),
    ]
