# Generated by Django 4.2.1 on 2023-08-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0014_alter_block_nonce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='block',
            new_name='Block',
        ),
    ]
