# Generated by Django 4.2.1 on 2023-08-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0015_rename_block_vote_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='Block',
            new_name='block',
        ),
    ]
