# Generated by Django 4.2.1 on 2023-08-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0016_rename_block_vote_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='hash_code',
            new_name='hash',
        ),
    ]
