# Generated by Django 4.2.1 on 2023-08-28 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0017_rename_hash_code_block_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='hash',
            new_name='hash_code',
        ),
    ]
