# Generated by Django 4.2.1 on 2023-08-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0020_alter_block_hash_code_alter_block_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='hash',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
